# Generated by Django 4.0.3 on 2022-04-09 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=250, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('phone_num', models.CharField(max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.CharField(max_length=100)),
                ('price', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_date', models.DateField(verbose_name='reported-Date')),
                ('incident_date', models.DateField(verbose_name='incident-Date')),
                ('incident_time', models.TimeField(verbose_name='incident-Time')),
                ('description', models.TextField(blank=True)),
                ('injury_description', models.TextField(blank=True)),
                ('first_aider', models.CharField(max_length=100)),
                ('injury_nature', models.CharField(max_length=200)),
                ('medical_needed', models.CharField(max_length=10)),
                ('empolyee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
                ('room_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnsafeCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Timeclaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_days', models.IntegerField()),
                ('report_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpsr.incident')),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_date', models.DateField(verbose_name='invest-Date')),
                ('incident_date', models.DateField(verbose_name='incident-Date')),
                ('incident_time', models.TimeField(verbose_name='incident-Time')),
                ('description', models.TextField(blank=True)),
                ('prevent_suggest', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpsr.location')),
                ('report_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpsr.incident')),
                ('task_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpsr.task')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpsr.location'),
        ),
        migrations.AddField(
            model_name='incident',
            name='task_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpsr.task'),
        ),
        migrations.CreateModel(
            name='DamageClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.TextField(blank=True)),
                ('invest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpsr.investigation')),
            ],
        ),
    ]
